version: 0.1
log:
  fields:
    service: registry
storage:
    cache:
        blobdescriptor: redis
    filesystem:
        rootdirectory: /var/lib/registry
    maintenance:
      uploadpurging:
        enabled: true
        age: 168h
        interval: 24h
        dryrun: false

http:
  addr: :5000
  net: tcp
  secret: supersecretuuid
  tls:
    certificate: /certs/domain.crt
    key: /certs/domain.key
    # clientcas:
    #   - /path/to/ca.pem
    #   - /path/to/another/ca.pem
  debug:
    addr: localhost:5001
  headers:
    X-Content-Type-Options: [nosniff]

redis:
  addr: cache:6379
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:
    maxidle: 16
    maxactive: 64
    idletimeout: 300s

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

auth:
  htpasswd:
    realm: basic-realm
    path: /auth/htpasswd
