
db:
  # get the latest mysql server
  image: mysql:5.6

  # Set db environment
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw

  # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
  volumes:
    - "mysql-data:/var/lib/mysql"
    - "/etc/localtime:/etc/localtime:ro"

php:
  build: ./php
  #default command in php container (see .php/Dockerfile)
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
  expose:
    - "9000"
  #links container togheter
  links:
    - db:mysql

  environment:
    PROJECT_NAME: blog
  
    
nginx:
  # get the latest nginx image
  build: ./nginx
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
  volumes_from:
    - php
  ports:
    - "10080:10080"
  links:
    - php
    