
db:
  # get the latest mysql server
  image: mysql:5.6

  # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
  volumes:
    - "mysql-data:/var/lib/mysql"

    
web:
  build: ./web
  command: python mysite/manage.py runserver 0.0.0.0:8000
  working_dir: /var/uwsgi/
  volumes:
    - "django-data/:/var/uwsgi/"
  ports:
    - "8000"
  links:
    - db
