
db:
  # get the latest mysql server
  image: mysql:5.6

  # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
  volumes:
    - "mysql-data:/var/lib/mysql"

    
web:
  build: ./web
  command: python manage.py runserver 0.0.0.0:8000
  working_dir: /home/django
  user: django
  #volumes:
  #  - "django-data:/home/django"
  ports:
    - "8000"
  links:
    - db
