
db:
  # get the latest mysql server
  image: mysql:5.6

  # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
  volumes:
    - "mysql-data:/var/lib/mysql"

    
web:
  build: ./web
  command: uwsgi --ini /etc/django_uwsgi.ini
  working_dir: /var/uwsgi/
  volumes:
    - "django-data/:/var/uwsgi/"
  #Expose ports without publishing them to the host machine
  expose:
    - "8000"
  links:
    - db

php:
  build: ./php
  #default command in php container
  expose:
    - "9000"
  links:
    - db
    
nginx:
  # get the latest nginx image
  build: ./nginx
  volumes_from:
    - web
    - php
  ports:
    - "10080:80"
  links:
    - web
    - php
    